// Generated file. Do not edit.
// This file is generated by the iFlutter

// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars
class FontRes {
  FontRes._();

  static const String PROJECT_NAME = 'travel_cost_planner_europe';
  static const String PROJECT_VERSION = '1.0.8+9';
  static const String NOTOSANS_BOLD = 'NotoSans-Bold';
  static const String NOTOSANS_REGULAR = 'NotoSans-Regular';
}
