import 'package:flutter_gen/gen_l10n/app_localizations.dart';

/// Resolver for transport and season-specific packing template keys.
String? resolveTransportPackingTemplateKey(AppLocalizations l10n, String key) {
  switch (key) {
    case 'packingTemplateBicycle':
      return l10n.packingTemplateBicycle;
    case 'packingTemplateBicycleDesc':
      return l10n.packingTemplateBicycleDesc;
    case 'packingTemplateCamper':
      return l10n.packingTemplateCamper;
    case 'packingTemplateCamperDesc':
      return l10n.packingTemplateCamperDesc;
    case 'packingTemplateCarTravel':
      return l10n.packingTemplateCarTravel;
    case 'packingTemplateCarTravelDesc':
      return l10n.packingTemplateCarTravelDesc;
    case 'packingTemplateCategoryBabyCare':
      return l10n.packingTemplateCategoryBabyCare;
    case 'packingTemplateCategoryBicycleGear':
      return l10n.packingTemplateCategoryBicycleGear;
    case 'packingTemplateCategoryCamperGear':
      return l10n.packingTemplateCategoryCamperGear;
    case 'packingTemplateCategoryCatCare':
      return l10n.packingTemplateCategoryCatCare;
    case 'packingTemplateCategoryDocuments':
      return l10n.packingTemplateCategoryDocuments;
    case 'packingTemplateCategoryElectronics':
      return l10n.packingTemplateCategoryElectronics;
    case 'packingTemplateCategoryEmergencyTools':
      return l10n.packingTemplateCategoryEmergencyTools;
    case 'packingTemplateCategoryFinalDepartureChecks':
      return l10n.packingTemplateCategoryFinalDepartureChecks;
    case 'packingTemplateCategoryLightsVisibility':
      return l10n.packingTemplateCategoryLightsVisibility;
    case 'packingTemplateCategoryLuggageLoading':
      return l10n.packingTemplateCategoryLuggageLoading;
    case 'packingTemplateCategoryMotorcycleGear':
      return l10n.packingTemplateCategoryMotorcycleGear;
    case 'packingTemplateCategoryRoutePreparation':
      return l10n.packingTemplateCategoryRoutePreparation;
    case 'packingTemplateCategorySafetyEquipment':
      return l10n.packingTemplateCategorySafetyEquipment;
    case 'packingTemplateCategorySummerGear':
      return l10n.packingTemplateCategorySummerGear;
    case 'packingTemplateCategoryTyresBrakes':
      return l10n.packingTemplateCategoryTyresBrakes;
    case 'packingTemplateCategoryVehicleFluids':
      return l10n.packingTemplateCategoryVehicleFluids;
    case 'packingTemplateCategoryWinterGear':
      return l10n.packingTemplateCategoryWinterGear;
    case 'packingTemplateGroupTransport':
      return l10n.packingTemplateGroupTransport;
    case 'packingTemplateGroupTravellers':
      return l10n.packingTemplateGroupTravellers;
    case 'packingTemplateGroupTripType':
      return l10n.packingTemplateGroupTripType;
    case 'packingTemplateItemBabyBath':
      return l10n.packingTemplateItemBabyBath;
    case 'packingTemplateItemBabyBibs':
      return l10n.packingTemplateItemBabyBibs;
    case 'packingTemplateItemBabyBlanket':
      return l10n.packingTemplateItemBabyBlanket;
    case 'packingTemplateItemBabyBooks':
      return l10n.packingTemplateItemBabyBooks;
    case 'packingTemplateItemBabyBoosterSeat':
      return l10n.packingTemplateItemBabyBoosterSeat;
    case 'packingTemplateItemBabyBottleBrush':
      return l10n.packingTemplateItemBabyBottleBrush;
    case 'packingTemplateItemBabyBottles':
      return l10n.packingTemplateItemBabyBottles;
    case 'packingTemplateItemBabyBreastPump':
      return l10n.packingTemplateItemBabyBreastPump;
    case 'packingTemplateItemBabyCabinetLocks':
      return l10n.packingTemplateItemBabyCabinetLocks;
    case 'packingTemplateItemBabyCarSeat':
      return l10n.packingTemplateItemBabyCarSeat;
    case 'packingTemplateItemBabyCarrier':
      return l10n.packingTemplateItemBabyCarrier;
    case 'packingTemplateItemBabyChangingMat':
      return l10n.packingTemplateItemBabyChangingMat;
    case 'packingTemplateItemBabyClothes':
      return l10n.packingTemplateItemBabyClothes;
    case 'packingTemplateItemBabyCoolerBags':
      return l10n.packingTemplateItemBabyCoolerBags;
    case 'packingTemplateItemBabyEmergencyContacts':
      return l10n.packingTemplateItemBabyEmergencyContacts;
    case 'packingTemplateItemBabyFirstAid':
      return l10n.packingTemplateItemBabyFirstAid;
    case 'packingTemplateItemBabyFood':
      return l10n.packingTemplateItemBabyFood;
    case 'packingTemplateItemBabyFormula':
      return l10n.packingTemplateItemBabyFormula;
    case 'packingTemplateItemBabyGate':
      return l10n.packingTemplateItemBabyGate;
    case 'packingTemplateItemBabyHat':
      return l10n.packingTemplateItemBabyHat;
    case 'packingTemplateItemBabyHealthRecords':
      return l10n.packingTemplateItemBabyHealthRecords;
    case 'packingTemplateItemBabyHighChair':
      return l10n.packingTemplateItemBabyHighChair;
    case 'packingTemplateItemBabyLaundryBags':
      return l10n.packingTemplateItemBabyLaundryBags;
    case 'packingTemplateItemBabyLotion':
      return l10n.packingTemplateItemBabyLotion;
    case 'packingTemplateItemBabyMedicationList':
      return l10n.packingTemplateItemBabyMedicationList;
    case 'packingTemplateItemBabyMedicine':
      return l10n.packingTemplateItemBabyMedicine;
    case 'packingTemplateItemBabyMilkStorage':
      return l10n.packingTemplateItemBabyMilkStorage;
    case 'packingTemplateItemBabyMonitor':
      return l10n.packingTemplateItemBabyMonitor;
    case 'packingTemplateItemBabyNappyBags':
      return l10n.packingTemplateItemBabyNappyBags;
    case 'packingTemplateItemBabyNasalAspirator':
      return l10n.packingTemplateItemBabyNasalAspirator;
    case 'packingTemplateItemBabyNightLight':
      return l10n.packingTemplateItemBabyNightLight;
    case 'packingTemplateItemBabyNursingCover':
      return l10n.packingTemplateItemBabyNursingCover;
    case 'packingTemplateItemBabyOutletCovers':
      return l10n.packingTemplateItemBabyOutletCovers;
    case 'packingTemplateItemBabyPacifier':
      return l10n.packingTemplateItemBabyPacifier;
    case 'packingTemplateItemBabyPassport':
      return l10n.packingTemplateItemBabyPassport;
    case 'packingTemplateItemBabyPortablePotty':
      return l10n.packingTemplateItemBabyPortablePotty;
    case 'packingTemplateItemBabyPottySeat':
      return l10n.packingTemplateItemBabyPottySeat;
    case 'packingTemplateItemBabyRashCream':
      return l10n.packingTemplateItemBabyRashCream;
    case 'packingTemplateItemBabyShampoo':
      return l10n.packingTemplateItemBabyShampoo;
    case 'packingTemplateItemBabyShoes':
      return l10n.packingTemplateItemBabyShoes;
    case 'packingTemplateItemBabySippyCup':
      return l10n.packingTemplateItemBabySippyCup;
    case 'packingTemplateItemBabySleepingBag':
      return l10n.packingTemplateItemBabySleepingBag;
    case 'packingTemplateItemBabySnacks':
      return l10n.packingTemplateItemBabySnacks;
    case 'packingTemplateItemBabySocks':
      return l10n.packingTemplateItemBabySocks;
    case 'packingTemplateItemBabySpillMat':
      return l10n.packingTemplateItemBabySpillMat;
    case 'packingTemplateItemBabySterilizer':
      return l10n.packingTemplateItemBabySterilizer;
    case 'packingTemplateItemBabyStroller':
      return l10n.packingTemplateItemBabyStroller;
    case 'packingTemplateItemBabyStrollerRainCover':
      return l10n.packingTemplateItemBabyStrollerRainCover;
    case 'packingTemplateItemBabyStrollerSunshade':
      return l10n.packingTemplateItemBabyStrollerSunshade;
    case 'packingTemplateItemBabySunHat':
      return l10n.packingTemplateItemBabySunHat;
    case 'packingTemplateItemBabySunscreen':
      return l10n.packingTemplateItemBabySunscreen;
    case 'packingTemplateItemBabyTeether':
      return l10n.packingTemplateItemBabyTeether;
    case 'packingTemplateItemBabyTowel':
      return l10n.packingTemplateItemBabyTowel;
    case 'packingTemplateItemBabyTravelCot':
      return l10n.packingTemplateItemBabyTravelCot;
    case 'packingTemplateItemBabyTravelInsurance':
      return l10n.packingTemplateItemBabyTravelInsurance;
    case 'packingTemplateItemBabyWhiteNoise':
      return l10n.packingTemplateItemBabyWhiteNoise;
    case 'packingTemplateItemBabyWipes':
      return l10n.packingTemplateItemBabyWipes;
    case 'packingTemplateItemBikeArmWarmers':
      return l10n.packingTemplateItemBikeArmWarmers;
    case 'packingTemplateItemBikeBag':
      return l10n.packingTemplateItemBikeBag;
    case 'packingTemplateItemBikeBell':
      return l10n.packingTemplateItemBikeBell;
    case 'packingTemplateItemBikeBottleCage':
      return l10n.packingTemplateItemBikeBottleCage;
    case 'packingTemplateItemBikeChainLube':
      return l10n.packingTemplateItemBikeChainLube;
    case 'packingTemplateItemBikeCleats':
      return l10n.packingTemplateItemBikeCleats;
    case 'packingTemplateItemBikeComputer':
      return l10n.packingTemplateItemBikeComputer;
    case 'packingTemplateItemBikeCyclingGloves':
      return l10n.packingTemplateItemBikeCyclingGloves;
    case 'packingTemplateItemBikeCyclingShoes':
      return l10n.packingTemplateItemBikeCyclingShoes;
    case 'packingTemplateItemBikeCyclingShorts':
      return l10n.packingTemplateItemBikeCyclingShorts;
    case 'packingTemplateItemBikeEnergyGels':
      return l10n.packingTemplateItemBikeEnergyGels;
    case 'packingTemplateItemBikeHelmet':
      return l10n.packingTemplateItemBikeHelmet;
    case 'packingTemplateItemBikeJersey':
      return l10n.packingTemplateItemBikeJersey;
    case 'packingTemplateItemBikeLegWarmers':
      return l10n.packingTemplateItemBikeLegWarmers;
    case 'packingTemplateItemBikeLightsFront':
      return l10n.packingTemplateItemBikeLightsFront;
    case 'packingTemplateItemBikeLightsRear':
      return l10n.packingTemplateItemBikeLightsRear;
    case 'packingTemplateItemBikeLock':
      return l10n.packingTemplateItemBikeLock;
    case 'packingTemplateItemBikePanniers':
      return l10n.packingTemplateItemBikePanniers;
    case 'packingTemplateItemBikePatchKit':
      return l10n.packingTemplateItemBikePatchKit;
    case 'packingTemplateItemBikePhoneMount':
      return l10n.packingTemplateItemBikePhoneMount;
    case 'packingTemplateItemBikePump':
      return l10n.packingTemplateItemBikePump;
    case 'packingTemplateItemBikeReflectors':
      return l10n.packingTemplateItemBikeReflectors;
    case 'packingTemplateItemBikeRepairKit':
      return l10n.packingTemplateItemBikeRepairKit;
    case 'packingTemplateItemBikeSaddleCover':
      return l10n.packingTemplateItemBikeSaddleCover;
    case 'packingTemplateItemBikeSpareChainLink':
      return l10n.packingTemplateItemBikeSpareChainLink;
    case 'packingTemplateItemBikeSpareTubes':
      return l10n.packingTemplateItemBikeSpareTubes;
    case 'packingTemplateItemBikeTireLevers':
      return l10n.packingTemplateItemBikeTireLevers;
    case 'packingTemplateItemCamperAdapterPlug':
      return l10n.packingTemplateItemCamperAdapterPlug;
    case 'packingTemplateItemCamperAwning':
      return l10n.packingTemplateItemCamperAwning;
    case 'packingTemplateItemCamperAwningLight':
      return l10n.packingTemplateItemCamperAwningLight;
    case 'packingTemplateItemCamperAwningPegs':
      return l10n.packingTemplateItemCamperAwningPegs;
    case 'packingTemplateItemCamperBarbecue':
      return l10n.packingTemplateItemCamperBarbecue;
    case 'packingTemplateItemCamperBedding':
      return l10n.packingTemplateItemCamperBedding;
    case 'packingTemplateItemCamperBikeRack':
      return l10n.packingTemplateItemCamperBikeRack;
    case 'packingTemplateItemCamperCampingChairs':
      return l10n.packingTemplateItemCamperCampingChairs;
    case 'packingTemplateItemCamperCampingCutlery':
      return l10n.packingTemplateItemCamperCampingCutlery;
    case 'packingTemplateItemCamperCampingTable':
      return l10n.packingTemplateItemCamperCampingTable;
    case 'packingTemplateItemCamperCharcoal':
      return l10n.packingTemplateItemCamperCharcoal;
    case 'packingTemplateItemCamperChemicalToilet':
      return l10n.packingTemplateItemCamperChemicalToilet;
    case 'packingTemplateItemCamperCleaningSupplies':
      return l10n.packingTemplateItemCamperCleaningSupplies;
    case 'packingTemplateItemCamperCoDetector':
      return l10n.packingTemplateItemCamperCoDetector;
    case 'packingTemplateItemCamperCookware':
      return l10n.packingTemplateItemCamperCookware;
    case 'packingTemplateItemCamperCoolbox':
      return l10n.packingTemplateItemCamperCoolbox;
    case 'packingTemplateItemCamperCurtainTies':
      return l10n.packingTemplateItemCamperCurtainTies;
    case 'packingTemplateItemCamperDishWashing':
      return l10n.packingTemplateItemCamperDishWashing;
    case 'packingTemplateItemCamperFreshWaterHose':
      return l10n.packingTemplateItemCamperFreshWaterHose;
    case 'packingTemplateItemCamperFuseKit':
      return l10n.packingTemplateItemCamperFuseKit;
    case 'packingTemplateItemCamperGasBottle':
      return l10n.packingTemplateItemCamperGasBottle;
    case 'packingTemplateItemCamperGasRegulator':
      return l10n.packingTemplateItemCamperGasRegulator;
    case 'packingTemplateItemCamperGroundSheet':
      return l10n.packingTemplateItemCamperGroundSheet;
    case 'packingTemplateItemCamperHookupCable':
      return l10n.packingTemplateItemCamperHookupCable;
    case 'packingTemplateItemCamperHoseFittings':
      return l10n.packingTemplateItemCamperHoseFittings;
    case 'packingTemplateItemCamperInsectScreen':
      return l10n.packingTemplateItemCamperInsectScreen;
    case 'packingTemplateItemCamperKitchenUtensils':
      return l10n.packingTemplateItemCamperKitchenUtensils;
    case 'packingTemplateItemCamperLevelingBlocks':
      return l10n.packingTemplateItemCamperLevelingBlocks;
    case 'packingTemplateItemCamperMallet':
      return l10n.packingTemplateItemCamperMallet;
    case 'packingTemplateItemCamperMatches':
      return l10n.packingTemplateItemCamperMatches;
    case 'packingTemplateItemCamperOutdoorRug':
      return l10n.packingTemplateItemCamperOutdoorRug;
    case 'packingTemplateItemCamperPillows':
      return l10n.packingTemplateItemCamperPillows;
    case 'packingTemplateItemCamperRoofLadder':
      return l10n.packingTemplateItemCamperRoofLadder;
    case 'packingTemplateItemCamperSatelliteDish':
      return l10n.packingTemplateItemCamperSatelliteDish;
    case 'packingTemplateItemCamperSmokeDetector':
      return l10n.packingTemplateItemCamperSmokeDetector;
    case 'packingTemplateItemCamperSpareBulbs':
      return l10n.packingTemplateItemCamperSpareBulbs;
    case 'packingTemplateItemCamperToiletPaper':
      return l10n.packingTemplateItemCamperToiletPaper;
    case 'packingTemplateItemCamperToolkit':
      return l10n.packingTemplateItemCamperToolkit;
    case 'packingTemplateItemCamperTvAerial':
      return l10n.packingTemplateItemCamperTvAerial;
    case 'packingTemplateItemCamperWasteHose':
      return l10n.packingTemplateItemCamperWasteHose;
    case 'packingTemplateItemCamperWaterContainers':
      return l10n.packingTemplateItemCamperWaterContainers;
    case 'packingTemplateItemCamperWaterFilter':
      return l10n.packingTemplateItemCamperWaterFilter;
    case 'packingTemplateItemCampingStove':
      return l10n.packingTemplateItemCampingStove;
    case 'packingTemplateItemCarDocuments':
      return l10n.packingTemplateItemCarDocuments;
    case 'packingTemplateItemCatBed':
      return l10n.packingTemplateItemCatBed;
    case 'packingTemplateItemCatBlanket':
      return l10n.packingTemplateItemCatBlanket;
    case 'packingTemplateItemCatCalmingSpray':
      return l10n.packingTemplateItemCatCalmingSpray;
    case 'packingTemplateItemCatCarrierLiner':
      return l10n.packingTemplateItemCatCarrierLiner;
    case 'packingTemplateItemCatCoolingMat':
      return l10n.packingTemplateItemCatCoolingMat;
    case 'packingTemplateItemCatEntryPermit':
      return l10n.packingTemplateItemCatEntryPermit;
    case 'packingTemplateItemCatFoodBowls':
      return l10n.packingTemplateItemCatFoodBowls;
    case 'packingTemplateItemCatFoodPuzzle':
      return l10n.packingTemplateItemCatFoodPuzzle;
    case 'packingTemplateItemCatGroomingBrush':
      return l10n.packingTemplateItemCatGroomingBrush;
    case 'packingTemplateItemCatHarness':
      return l10n.packingTemplateItemCatHarness;
    case 'packingTemplateItemCatHeatingPad':
      return l10n.packingTemplateItemCatHeatingPad;
    case 'packingTemplateItemCatIdTag':
      return l10n.packingTemplateItemCatIdTag;
    case 'packingTemplateItemCatLitter':
      return l10n.packingTemplateItemCatLitter;
    case 'packingTemplateItemCatLitterBox':
      return l10n.packingTemplateItemCatLitterBox;
    case 'packingTemplateItemCatLitterScoop':
      return l10n.packingTemplateItemCatLitterScoop;
    case 'packingTemplateItemCatMedication':
      return l10n.packingTemplateItemCatMedication;
    case 'packingTemplateItemCatMicrochip':
      return l10n.packingTemplateItemCatMicrochip;
    case 'packingTemplateItemCatNailClippers':
      return l10n.packingTemplateItemCatNailClippers;
    case 'packingTemplateItemCatPassport':
      return l10n.packingTemplateItemCatPassport;
    case 'packingTemplateItemCatPetInsurance':
      return l10n.packingTemplateItemCatPetInsurance;
    case 'packingTemplateItemCatPheromone':
      return l10n.packingTemplateItemCatPheromone;
    case 'packingTemplateItemCatPortableFence':
      return l10n.packingTemplateItemCatPortableFence;
    case 'packingTemplateItemCatRecentPhoto':
      return l10n.packingTemplateItemCatRecentPhoto;
    case 'packingTemplateItemCatScratchingPad':
      return l10n.packingTemplateItemCatScratchingPad;
    case 'packingTemplateItemCatSeatBeltClip':
      return l10n.packingTemplateItemCatSeatBeltClip;
    case 'packingTemplateItemCatTranquilizer':
      return l10n.packingTemplateItemCatTranquilizer;
    case 'packingTemplateItemCatTravelLitter':
      return l10n.packingTemplateItemCatTravelLitter;
    case 'packingTemplateItemCatTreats':
      return l10n.packingTemplateItemCatTreats;
    case 'packingTemplateItemCatVaccination':
      return l10n.packingTemplateItemCatVaccination;
    case 'packingTemplateItemCatVetContact':
      return l10n.packingTemplateItemCatVetContact;
    case 'packingTemplateItemCatWasteBags':
      return l10n.packingTemplateItemCatWasteBags;
    case 'packingTemplateItemCatWaterFountain':
      return l10n.packingTemplateItemCatWaterFountain;
    case 'packingTemplateItemCatWindowScreen':
      return l10n.packingTemplateItemCatWindowScreen;
    case 'packingTemplateItemCatWipes':
      return l10n.packingTemplateItemCatWipes;
    case 'packingTemplateItemDiapers':
      return l10n.packingTemplateItemDiapers;
    case 'packingTemplateItemDrivingLicense':
      return l10n.packingTemplateItemDrivingLicense;
    case 'packingTemplateItemFavoriteToy':
      return l10n.packingTemplateItemFavoriteToy;
    case 'packingTemplateItemFirstAidKit':
      return l10n.packingTemplateItemFirstAidKit;
    case 'packingTemplateItemFlashlight':
      return l10n.packingTemplateItemFlashlight;
    case 'packingTemplateItemFuelCard':
      return l10n.packingTemplateItemFuelCard;
    case 'packingTemplateItemHealthThermometer':
      return l10n.packingTemplateItemHealthThermometer;
    case 'packingTemplateItemLeash':
      return l10n.packingTemplateItemLeash;
    case 'packingTemplateItemMotoBalaclava':
      return l10n.packingTemplateItemMotoBalaclava;
    case 'packingTemplateItemMotoBoots':
      return l10n.packingTemplateItemMotoBoots;
    case 'packingTemplateItemMotoBungeeCords':
      return l10n.packingTemplateItemMotoBungeeCords;
    case 'packingTemplateItemMotoChainLock':
      return l10n.packingTemplateItemMotoChainLock;
    case 'packingTemplateItemMotoChainLube':
      return l10n.packingTemplateItemMotoChainLube;
    case 'packingTemplateItemMotoCover':
      return l10n.packingTemplateItemMotoCover;
    case 'packingTemplateItemMotoDiscLock':
      return l10n.packingTemplateItemMotoDiscLock;
    case 'packingTemplateItemMotoDocuments':
      return l10n.packingTemplateItemMotoDocuments;
    case 'packingTemplateItemMotoEarPlugs':
      return l10n.packingTemplateItemMotoEarPlugs;
    case 'packingTemplateItemMotoEmergencyContact':
      return l10n.packingTemplateItemMotoEmergencyContact;
    case 'packingTemplateItemMotoGloves':
      return l10n.packingTemplateItemMotoGloves;
    case 'packingTemplateItemMotoHelmet':
      return l10n.packingTemplateItemMotoHelmet;
    case 'packingTemplateItemMotoHydrationPack':
      return l10n.packingTemplateItemMotoHydrationPack;
    case 'packingTemplateItemMotoIntercom':
      return l10n.packingTemplateItemMotoIntercom;
    case 'packingTemplateItemMotoJacket':
      return l10n.packingTemplateItemMotoJacket;
    case 'packingTemplateItemMotoNeckBrace':
      return l10n.packingTemplateItemMotoNeckBrace;
    case 'packingTemplateItemMotoPhoneMount':
      return l10n.packingTemplateItemMotoPhoneMount;
    case 'packingTemplateItemMotoProtectivePads':
      return l10n.packingTemplateItemMotoProtectivePads;
    case 'packingTemplateItemMotoRainCovers':
      return l10n.packingTemplateItemMotoRainCovers;
    case 'packingTemplateItemMotoRainGloves':
      return l10n.packingTemplateItemMotoRainGloves;
    case 'packingTemplateItemMotoRainSuit':
      return l10n.packingTemplateItemMotoRainSuit;
    case 'packingTemplateItemMotoReflectiveTape':
      return l10n.packingTemplateItemMotoReflectiveTape;
    case 'packingTemplateItemMotoSaddlebags':
      return l10n.packingTemplateItemMotoSaddlebags;
    case 'packingTemplateItemMotoSpareGloves':
      return l10n.packingTemplateItemMotoSpareGloves;
    case 'packingTemplateItemMotoSpareKey':
      return l10n.packingTemplateItemMotoSpareKey;
    case 'packingTemplateItemMotoSpareVisor':
      return l10n.packingTemplateItemMotoSpareVisor;
    case 'packingTemplateItemMotoTankBag':
      return l10n.packingTemplateItemMotoTankBag;
    case 'packingTemplateItemMotoTireRepair':
      return l10n.packingTemplateItemMotoTireRepair;
    case 'packingTemplateItemMotoToolkit':
      return l10n.packingTemplateItemMotoToolkit;
    case 'packingTemplateItemMotoTrousers':
      return l10n.packingTemplateItemMotoTrousers;
    case 'packingTemplateItemMotoUsbCharger':
      return l10n.packingTemplateItemMotoUsbCharger;
    case 'packingTemplateItemMotoVisorCleaner':
      return l10n.packingTemplateItemMotoVisorCleaner;
    case 'packingTemplateItemPetCarrier':
      return l10n.packingTemplateItemPetCarrier;
    case 'packingTemplateItemPetFood':
      return l10n.packingTemplateItemPetFood;
    case 'packingTemplateItemPetHealthRecords':
      return l10n.packingTemplateItemPetHealthRecords;
    case 'packingTemplateItemPetWaterBowl':
      return l10n.packingTemplateItemPetWaterBowl;
    case 'packingTemplateItemRoadsideKit':
      return l10n.packingTemplateItemRoadsideKit;
    case 'packingTemplateItemRtAdBlue':
      return l10n.packingTemplateItemRtAdBlue;
    case 'packingTemplateItemRtBluetoothHandsfree':
      return l10n.packingTemplateItemRtBluetoothHandsfree;
    case 'packingTemplateItemRtBorderCrossingInfo':
      return l10n.packingTemplateItemRtBorderCrossingInfo;
    case 'packingTemplateItemRtBrakeFluidCheck':
      return l10n.packingTemplateItemRtBrakeFluidCheck;
    case 'packingTemplateItemRtBrakeLightsCheck':
      return l10n.packingTemplateItemRtBrakeLightsCheck;
    case 'packingTemplateItemRtBrakePadsCheck':
      return l10n.packingTemplateItemRtBrakePadsCheck;
    case 'packingTemplateItemRtCarPhoneMount':
      return l10n.packingTemplateItemRtCarPhoneMount;
    case 'packingTemplateItemRtChargingCables':
      return l10n.packingTemplateItemRtChargingCables;
    case 'packingTemplateItemRtCoolantCheck':
      return l10n.packingTemplateItemRtCoolantCheck;
    case 'packingTemplateItemRtDashCam':
      return l10n.packingTemplateItemRtDashCam;
    case 'packingTemplateItemRtDashCamSdCard':
      return l10n.packingTemplateItemRtDashCamSdCard;
    case 'packingTemplateItemRtDocumentsInCar':
      return l10n.packingTemplateItemRtDocumentsInCar;
    case 'packingTemplateItemRtDuctTape':
      return l10n.packingTemplateItemRtDuctTape;
    case 'packingTemplateItemRtEmergencyBlanket':
      return l10n.packingTemplateItemRtEmergencyBlanket;
    case 'packingTemplateItemRtEmergencyKitAccessible':
      return l10n.packingTemplateItemRtEmergencyKitAccessible;
    case 'packingTemplateItemRtEmergencyNumbers':
      return l10n.packingTemplateItemRtEmergencyNumbers;
    case 'packingTemplateItemRtEngineOilCheck':
      return l10n.packingTemplateItemRtEngineOilCheck;
    case 'packingTemplateItemRtExteriorLightsCheck':
      return l10n.packingTemplateItemRtExteriorLightsCheck;
    case 'packingTemplateItemRtFireExtinguisher':
      return l10n.packingTemplateItemRtFireExtinguisher;
    case 'packingTemplateItemRtFuelPlan':
      return l10n.packingTemplateItemRtFuelPlan;
    case 'packingTemplateItemRtFuelTankFull':
      return l10n.packingTemplateItemRtFuelTankFull;
    case 'packingTemplateItemRtGpsNavigation':
      return l10n.packingTemplateItemRtGpsNavigation;
    case 'packingTemplateItemRtGreenCard':
      return l10n.packingTemplateItemRtGreenCard;
    case 'packingTemplateItemRtHeadlightBeamAdjust':
      return l10n.packingTemplateItemRtHeadlightBeamAdjust;
    case 'packingTemplateItemRtHighVisVest':
      return l10n.packingTemplateItemRtHighVisVest;
    case 'packingTemplateItemRtHighVisVestsSet':
      return l10n.packingTemplateItemRtHighVisVestsSet;
    case 'packingTemplateItemRtIndicatorsCheck':
      return l10n.packingTemplateItemRtIndicatorsCheck;
    case 'packingTemplateItemRtInsectRepellent':
      return l10n.packingTemplateItemRtInsectRepellent;
    case 'packingTemplateItemRtInsuranceProof':
      return l10n.packingTemplateItemRtInsuranceProof;
    case 'packingTemplateItemRtJack':
      return l10n.packingTemplateItemRtJack;
    case 'packingTemplateItemRtJumpLeads':
      return l10n.packingTemplateItemRtJumpLeads;
    case 'packingTemplateItemRtLuggageLoaded':
      return l10n.packingTemplateItemRtLuggageLoaded;
    case 'packingTemplateItemRtMirrorsAdjusted':
      return l10n.packingTemplateItemRtMirrorsAdjusted;
    case 'packingTemplateItemRtMultiTool':
      return l10n.packingTemplateItemRtMultiTool;
    case 'packingTemplateItemRtNavigationSet':
      return l10n.packingTemplateItemRtNavigationSet;
    case 'packingTemplateItemRtOfflineMaps':
      return l10n.packingTemplateItemRtOfflineMaps;
    case 'packingTemplateItemRtPortableJumpStarter':
      return l10n.packingTemplateItemRtPortableJumpStarter;
    case 'packingTemplateItemRtPunctureKit':
      return l10n.packingTemplateItemRtPunctureKit;
    case 'packingTemplateItemRtRearLightsCheck':
      return l10n.packingTemplateItemRtRearLightsCheck;
    case 'packingTemplateItemRtRestStops':
      return l10n.packingTemplateItemRtRestStops;
    case 'packingTemplateItemRtRoadsideAssistance':
      return l10n.packingTemplateItemRtRoadsideAssistance;
    case 'packingTemplateItemRtRoofBoxSecured':
      return l10n.packingTemplateItemRtRoofBoxSecured;
    case 'packingTemplateItemRtRoutePlan':
      return l10n.packingTemplateItemRtRoutePlan;
    case 'packingTemplateItemRtSnowChains':
      return l10n.packingTemplateItemRtSnowChains;
    case 'packingTemplateItemRtSpareHeadlightBulbs':
      return l10n.packingTemplateItemRtSpareHeadlightBulbs;
    case 'packingTemplateItemRtSpareTyre':
      return l10n.packingTemplateItemRtSpareTyre;
    case 'packingTemplateItemRtSunShade':
      return l10n.packingTemplateItemRtSunShade;
    case 'packingTemplateItemRtTollBadge':
      return l10n.packingTemplateItemRtTollBadge;
    case 'packingTemplateItemRtTollRoutes':
      return l10n.packingTemplateItemRtTollRoutes;
    case 'packingTemplateItemRtTrafficRules':
      return l10n.packingTemplateItemRtTrafficRules;
    case 'packingTemplateItemRtTrailerHitchCheck':
      return l10n.packingTemplateItemRtTrailerHitchCheck;
    case 'packingTemplateItemRtTrailerLightsCheck':
      return l10n.packingTemplateItemRtTrailerLightsCheck;
    case 'packingTemplateItemRtTrashBags':
      return l10n.packingTemplateItemRtTrashBags;
    case 'packingTemplateItemRtTyreInflator':
      return l10n.packingTemplateItemRtTyreInflator;
    case 'packingTemplateItemRtTyrePressure':
      return l10n.packingTemplateItemRtTyrePressure;
    case 'packingTemplateItemRtTyreTread':
      return l10n.packingTemplateItemRtTyreTread;
    case 'packingTemplateItemRtTyresRecheck':
      return l10n.packingTemplateItemRtTyresRecheck;
    case 'packingTemplateItemRtUsbCarCharger':
      return l10n.packingTemplateItemRtUsbCarCharger;
    case 'packingTemplateItemRtVehicleRegistration':
      return l10n.packingTemplateItemRtVehicleRegistration;
    case 'packingTemplateItemRtVignetteReceipts':
      return l10n.packingTemplateItemRtVignetteReceipts;
    case 'packingTemplateItemRtVignetteRequirements':
      return l10n.packingTemplateItemRtVignetteRequirements;
    case 'packingTemplateItemRtWarningTriangle':
      return l10n.packingTemplateItemRtWarningTriangle;
    case 'packingTemplateItemRtWasherFluid':
      return l10n.packingTemplateItemRtWasherFluid;
    case 'packingTemplateItemRtWheelChocks':
      return l10n.packingTemplateItemRtWheelChocks;
    case 'packingTemplateItemRtWheelWrench':
      return l10n.packingTemplateItemRtWheelWrench;
    case 'packingTemplateItemRtWorkGloves':
      return l10n.packingTemplateItemRtWorkGloves;
    case 'packingTemplateItemSleepingBag':
      return l10n.packingTemplateItemSleepingBag;
    case 'packingTemplateItemSummerAfterSun':
      return l10n.packingTemplateItemSummerAfterSun;
    case 'packingTemplateItemSummerAloeVera':
      return l10n.packingTemplateItemSummerAloeVera;
    case 'packingTemplateItemSummerBeachUmbrella':
      return l10n.packingTemplateItemSummerBeachUmbrella;
    case 'packingTemplateItemSummerCooler':
      return l10n.packingTemplateItemSummerCooler;
    case 'packingTemplateItemSummerCoolingTowel':
      return l10n.packingTemplateItemSummerCoolingTowel;
    case 'packingTemplateItemSummerHydrationTablets':
      return l10n.packingTemplateItemSummerHydrationTablets;
    case 'packingTemplateItemSummerLipBalmSpf':
      return l10n.packingTemplateItemSummerLipBalmSpf;
    case 'packingTemplateItemSummerPortableFan':
      return l10n.packingTemplateItemSummerPortableFan;
    case 'packingTemplateItemSummerSnorkel':
      return l10n.packingTemplateItemSummerSnorkel;
    case 'packingTemplateItemSunscreen':
      return l10n.packingTemplateItemSunscreen;
    case 'packingTemplateItemWinterAntifreeze':
      return l10n.packingTemplateItemWinterAntifreeze;
    case 'packingTemplateItemWinterBaseLayers':
      return l10n.packingTemplateItemWinterBaseLayers;
    case 'packingTemplateItemWinterDeicer':
      return l10n.packingTemplateItemWinterDeicer;
    case 'packingTemplateItemWinterEarMuffs':
      return l10n.packingTemplateItemWinterEarMuffs;
    case 'packingTemplateItemWinterHandWarmers':
      return l10n.packingTemplateItemWinterHandWarmers;
    case 'packingTemplateItemWinterHotDrinks':
      return l10n.packingTemplateItemWinterHotDrinks;
    case 'packingTemplateItemWinterIceScraper':
      return l10n.packingTemplateItemWinterIceScraper;
    case 'packingTemplateItemWinterNeckWarmer':
      return l10n.packingTemplateItemWinterNeckWarmer;
    case 'packingTemplateItemWinterSkiGloves':
      return l10n.packingTemplateItemWinterSkiGloves;
    case 'packingTemplateItemWinterSkiGoggles':
      return l10n.packingTemplateItemWinterSkiGoggles;
    case 'packingTemplateItemWinterSkiPants':
      return l10n.packingTemplateItemWinterSkiPants;
    case 'packingTemplateItemWinterSnowBrush':
      return l10n.packingTemplateItemWinterSnowBrush;
    case 'packingTemplateItemWinterTractionAids':
      return l10n.packingTemplateItemWinterTractionAids;
    case 'packingTemplateItemWinterWindshieldCover':
      return l10n.packingTemplateItemWinterWindshieldCover;
    case 'packingTemplateItemWinterWinterBoots':
      return l10n.packingTemplateItemWinterWinterBoots;
    case 'packingTemplateMotorcycle':
      return l10n.packingTemplateMotorcycle;
    case 'packingTemplateMotorcycleDesc':
      return l10n.packingTemplateMotorcycleDesc;
    case 'packingTemplateSummer':
      return l10n.packingTemplateSummer;
    case 'packingTemplateSummerDesc':
      return l10n.packingTemplateSummerDesc;
    case 'packingTemplateUnitPack':
      return l10n.packingTemplateUnitPack;
    case 'packingTemplateUnitPair':
      return l10n.packingTemplateUnitPair;
    case 'packingTemplateUnitPiece':
      return l10n.packingTemplateUnitPiece;
    case 'packingTemplateUnitSet':
      return l10n.packingTemplateUnitSet;
    case 'packingTemplateWinter':
      return l10n.packingTemplateWinter;
    case 'packingTemplateWinterDesc':
      return l10n.packingTemplateWinterDesc;
    case 'packingTemplateWithBaby':
      return l10n.packingTemplateWithBaby;
    case 'packingTemplateWithBabyDesc':
      return l10n.packingTemplateWithBabyDesc;
    case 'packingTemplateWithCat':
      return l10n.packingTemplateWithCat;
    case 'packingTemplateWithCatDesc':
      return l10n.packingTemplateWithCatDesc;
    default:
      return null;
  }
}
