import 'package:flutter_gen/gen_l10n/app_localizations.dart';

/// Resolver for road-trip / car-travel packing template keys.
String? resolveRoadTripPackingTemplateKey(AppLocalizations l10n, String key) {
  switch (key) {
    case 'packingTemplateCarTravel':
      return l10n.packingTemplateCarTravel;
    case 'packingTemplateCarTravelDesc':
      return l10n.packingTemplateCarTravelDesc;
    case 'packingTemplateCategoryDocuments':
      return l10n.packingTemplateCategoryDocuments;
    case 'packingTemplateCategoryElectronics':
      return l10n.packingTemplateCategoryElectronics;
    case 'packingTemplateCategoryEmergencyTools':
      return l10n.packingTemplateCategoryEmergencyTools;
    case 'packingTemplateCategoryFinalDepartureChecks':
      return l10n.packingTemplateCategoryFinalDepartureChecks;
    case 'packingTemplateCategoryLightsVisibility':
      return l10n.packingTemplateCategoryLightsVisibility;
    case 'packingTemplateCategoryLuggageLoading':
      return l10n.packingTemplateCategoryLuggageLoading;
    case 'packingTemplateCategoryRoutePreparation':
      return l10n.packingTemplateCategoryRoutePreparation;
    case 'packingTemplateCategorySafetyEquipment':
      return l10n.packingTemplateCategorySafetyEquipment;
    case 'packingTemplateCategoryTyresBrakes':
      return l10n.packingTemplateCategoryTyresBrakes;
    case 'packingTemplateCategoryVehicleFluids':
      return l10n.packingTemplateCategoryVehicleFluids;
    case 'packingTemplateGroupTransport':
      return l10n.packingTemplateGroupTransport;
    case 'packingTemplateItemCamperBikeRack':
      return l10n.packingTemplateItemCamperBikeRack;
    case 'packingTemplateItemCarDocuments':
      return l10n.packingTemplateItemCarDocuments;
    case 'packingTemplateItemDrivingLicense':
      return l10n.packingTemplateItemDrivingLicense;
    case 'packingTemplateItemFirstAidKit':
      return l10n.packingTemplateItemFirstAidKit;
    case 'packingTemplateItemFlashlight':
      return l10n.packingTemplateItemFlashlight;
    case 'packingTemplateItemFuelCard':
      return l10n.packingTemplateItemFuelCard;
    case 'packingTemplateItemRoadsideKit':
      return l10n.packingTemplateItemRoadsideKit;
    case 'packingTemplateItemRtAdBlue':
      return l10n.packingTemplateItemRtAdBlue;
    case 'packingTemplateItemRtBluetoothHandsfree':
      return l10n.packingTemplateItemRtBluetoothHandsfree;
    case 'packingTemplateItemRtBorderCrossingInfo':
      return l10n.packingTemplateItemRtBorderCrossingInfo;
    case 'packingTemplateItemRtBrakeFluidCheck':
      return l10n.packingTemplateItemRtBrakeFluidCheck;
    case 'packingTemplateItemRtBrakeLightsCheck':
      return l10n.packingTemplateItemRtBrakeLightsCheck;
    case 'packingTemplateItemRtBrakePadsCheck':
      return l10n.packingTemplateItemRtBrakePadsCheck;
    case 'packingTemplateItemRtCarPhoneMount':
      return l10n.packingTemplateItemRtCarPhoneMount;
    case 'packingTemplateItemRtChargingCables':
      return l10n.packingTemplateItemRtChargingCables;
    case 'packingTemplateItemRtCoolantCheck':
      return l10n.packingTemplateItemRtCoolantCheck;
    case 'packingTemplateItemRtDashCam':
      return l10n.packingTemplateItemRtDashCam;
    case 'packingTemplateItemRtDashCamSdCard':
      return l10n.packingTemplateItemRtDashCamSdCard;
    case 'packingTemplateItemRtDocumentsInCar':
      return l10n.packingTemplateItemRtDocumentsInCar;
    case 'packingTemplateItemRtDuctTape':
      return l10n.packingTemplateItemRtDuctTape;
    case 'packingTemplateItemRtEmergencyBlanket':
      return l10n.packingTemplateItemRtEmergencyBlanket;
    case 'packingTemplateItemRtEmergencyKitAccessible':
      return l10n.packingTemplateItemRtEmergencyKitAccessible;
    case 'packingTemplateItemRtEmergencyNumbers':
      return l10n.packingTemplateItemRtEmergencyNumbers;
    case 'packingTemplateItemRtEngineOilCheck':
      return l10n.packingTemplateItemRtEngineOilCheck;
    case 'packingTemplateItemRtExteriorLightsCheck':
      return l10n.packingTemplateItemRtExteriorLightsCheck;
    case 'packingTemplateItemRtFireExtinguisher':
      return l10n.packingTemplateItemRtFireExtinguisher;
    case 'packingTemplateItemRtFuelPlan':
      return l10n.packingTemplateItemRtFuelPlan;
    case 'packingTemplateItemRtFuelTankFull':
      return l10n.packingTemplateItemRtFuelTankFull;
    case 'packingTemplateItemRtGpsNavigation':
      return l10n.packingTemplateItemRtGpsNavigation;
    case 'packingTemplateItemRtGreenCard':
      return l10n.packingTemplateItemRtGreenCard;
    case 'packingTemplateItemRtHeadlightBeamAdjust':
      return l10n.packingTemplateItemRtHeadlightBeamAdjust;
    case 'packingTemplateItemRtHighVisVest':
      return l10n.packingTemplateItemRtHighVisVest;
    case 'packingTemplateItemRtHighVisVestsSet':
      return l10n.packingTemplateItemRtHighVisVestsSet;
    case 'packingTemplateItemRtIndicatorsCheck':
      return l10n.packingTemplateItemRtIndicatorsCheck;
    case 'packingTemplateItemRtInsuranceProof':
      return l10n.packingTemplateItemRtInsuranceProof;
    case 'packingTemplateItemRtJack':
      return l10n.packingTemplateItemRtJack;
    case 'packingTemplateItemRtJumpLeads':
      return l10n.packingTemplateItemRtJumpLeads;
    case 'packingTemplateItemRtLuggageLoaded':
      return l10n.packingTemplateItemRtLuggageLoaded;
    case 'packingTemplateItemRtMirrorsAdjusted':
      return l10n.packingTemplateItemRtMirrorsAdjusted;
    case 'packingTemplateItemRtMultiTool':
      return l10n.packingTemplateItemRtMultiTool;
    case 'packingTemplateItemRtNavigationSet':
      return l10n.packingTemplateItemRtNavigationSet;
    case 'packingTemplateItemRtOfflineMaps':
      return l10n.packingTemplateItemRtOfflineMaps;
    case 'packingTemplateItemRtPortableJumpStarter':
      return l10n.packingTemplateItemRtPortableJumpStarter;
    case 'packingTemplateItemRtPunctureKit':
      return l10n.packingTemplateItemRtPunctureKit;
    case 'packingTemplateItemRtRearLightsCheck':
      return l10n.packingTemplateItemRtRearLightsCheck;
    case 'packingTemplateItemRtRestStops':
      return l10n.packingTemplateItemRtRestStops;
    case 'packingTemplateItemRtRoadsideAssistance':
      return l10n.packingTemplateItemRtRoadsideAssistance;
    case 'packingTemplateItemRtRoofBoxSecured':
      return l10n.packingTemplateItemRtRoofBoxSecured;
    case 'packingTemplateItemRtRoutePlan':
      return l10n.packingTemplateItemRtRoutePlan;
    case 'packingTemplateItemRtSnowChains':
      return l10n.packingTemplateItemRtSnowChains;
    case 'packingTemplateItemRtSpareHeadlightBulbs':
      return l10n.packingTemplateItemRtSpareHeadlightBulbs;
    case 'packingTemplateItemRtSpareTyre':
      return l10n.packingTemplateItemRtSpareTyre;
    case 'packingTemplateItemRtTollBadge':
      return l10n.packingTemplateItemRtTollBadge;
    case 'packingTemplateItemRtTollRoutes':
      return l10n.packingTemplateItemRtTollRoutes;
    case 'packingTemplateItemRtTrafficRules':
      return l10n.packingTemplateItemRtTrafficRules;
    case 'packingTemplateItemRtTrailerHitchCheck':
      return l10n.packingTemplateItemRtTrailerHitchCheck;
    case 'packingTemplateItemRtTrailerLightsCheck':
      return l10n.packingTemplateItemRtTrailerLightsCheck;
    case 'packingTemplateItemRtTyreInflator':
      return l10n.packingTemplateItemRtTyreInflator;
    case 'packingTemplateItemRtTyrePressure':
      return l10n.packingTemplateItemRtTyrePressure;
    case 'packingTemplateItemRtTyreTread':
      return l10n.packingTemplateItemRtTyreTread;
    case 'packingTemplateItemRtTyresRecheck':
      return l10n.packingTemplateItemRtTyresRecheck;
    case 'packingTemplateItemRtUsbCarCharger':
      return l10n.packingTemplateItemRtUsbCarCharger;
    case 'packingTemplateItemRtVehicleRegistration':
      return l10n.packingTemplateItemRtVehicleRegistration;
    case 'packingTemplateItemRtVignetteReceipts':
      return l10n.packingTemplateItemRtVignetteReceipts;
    case 'packingTemplateItemRtVignetteRequirements':
      return l10n.packingTemplateItemRtVignetteRequirements;
    case 'packingTemplateItemRtWarningTriangle':
      return l10n.packingTemplateItemRtWarningTriangle;
    case 'packingTemplateItemRtWasherFluid':
      return l10n.packingTemplateItemRtWasherFluid;
    case 'packingTemplateItemRtWheelWrench':
      return l10n.packingTemplateItemRtWheelWrench;
    case 'packingTemplateItemRtWorkGloves':
      return l10n.packingTemplateItemRtWorkGloves;
    case 'packingTemplateUnitPack':
      return l10n.packingTemplateUnitPack;
    case 'packingTemplateUnitPair':
      return l10n.packingTemplateUnitPair;
    case 'packingTemplateUnitPiece':
      return l10n.packingTemplateUnitPiece;
    case 'packingTemplateUnitSet':
      return l10n.packingTemplateUnitSet;
    default:
      return null;
  }
}
