import 'package:flutter_gen/gen_l10n/app_localizations.dart';

/// Resolver for modular packing template keys (documents, clothing, etc.).
String? resolveModularPackingTemplateKey(AppLocalizations l10n, String key) {
  switch (key) {
    case 'packingTemplateAirTravel':
      return l10n.packingTemplateAirTravel;
    case 'packingTemplateAirTravelDesc':
      return l10n.packingTemplateAirTravelDesc;
    case 'packingTemplateBasicTrip':
      return l10n.packingTemplateBasicTrip;
    case 'packingTemplateBasicTripDesc':
      return l10n.packingTemplateBasicTripDesc;
    case 'packingTemplateBeach':
      return l10n.packingTemplateBeach;
    case 'packingTemplateBeachDesc':
      return l10n.packingTemplateBeachDesc;
    case 'packingTemplateBusinessTrip':
      return l10n.packingTemplateBusinessTrip;
    case 'packingTemplateBusinessTripDesc':
      return l10n.packingTemplateBusinessTripDesc;
    case 'packingTemplateCamping':
      return l10n.packingTemplateCamping;
    case 'packingTemplateCampingDesc':
      return l10n.packingTemplateCampingDesc;
    case 'packingTemplateCategoryBeachGear':
      return l10n.packingTemplateCategoryBeachGear;
    case 'packingTemplateCategoryBusiness':
      return l10n.packingTemplateCategoryBusiness;
    case 'packingTemplateCategoryChildCare':
      return l10n.packingTemplateCategoryChildCare;
    case 'packingTemplateCategoryClothing':
      return l10n.packingTemplateCategoryClothing;
    case 'packingTemplateCategoryDocuments':
      return l10n.packingTemplateCategoryDocuments;
    case 'packingTemplateCategoryElectronics':
      return l10n.packingTemplateCategoryElectronics;
    case 'packingTemplateCategoryFinalDepartureChecks':
      return l10n.packingTemplateCategoryFinalDepartureChecks;
    case 'packingTemplateCategoryFood':
      return l10n.packingTemplateCategoryFood;
    case 'packingTemplateCategoryHealth':
      return l10n.packingTemplateCategoryHealth;
    case 'packingTemplateCategoryHomePreparation':
      return l10n.packingTemplateCategoryHomePreparation;
    case 'packingTemplateCategoryOutdoor':
      return l10n.packingTemplateCategoryOutdoor;
    case 'packingTemplateCategoryPetCare':
      return l10n.packingTemplateCategoryPetCare;
    case 'packingTemplateCategoryToiletries':
      return l10n.packingTemplateCategoryToiletries;
    case 'packingTemplateCategoryTravelGear':
      return l10n.packingTemplateCategoryTravelGear;
    case 'packingTemplateClothing':
      return l10n.packingTemplateClothing;
    case 'packingTemplateClothingDesc':
      return l10n.packingTemplateClothingDesc;
    case 'packingTemplateDocuments':
      return l10n.packingTemplateDocuments;
    case 'packingTemplateDocumentsDesc':
      return l10n.packingTemplateDocumentsDesc;
    case 'packingTemplateElectronics':
      return l10n.packingTemplateElectronics;
    case 'packingTemplateElectronicsDesc':
      return l10n.packingTemplateElectronicsDesc;
    case 'packingTemplateFinalChecks':
      return l10n.packingTemplateFinalChecks;
    case 'packingTemplateFinalChecksDesc':
      return l10n.packingTemplateFinalChecksDesc;
    case 'packingTemplateFoodDrinks':
      return l10n.packingTemplateFoodDrinks;
    case 'packingTemplateFoodDrinksDesc':
      return l10n.packingTemplateFoodDrinksDesc;
    case 'packingTemplateGroupBeforeLeaving':
      return l10n.packingTemplateGroupBeforeLeaving;
    case 'packingTemplateGroupEssentials':
      return l10n.packingTemplateGroupEssentials;
    case 'packingTemplateGroupTransport':
      return l10n.packingTemplateGroupTransport;
    case 'packingTemplateGroupTravellers':
      return l10n.packingTemplateGroupTravellers;
    case 'packingTemplateGroupTripType':
      return l10n.packingTemplateGroupTripType;
    case 'packingTemplateHealth':
      return l10n.packingTemplateHealth;
    case 'packingTemplateHealthDesc':
      return l10n.packingTemplateHealthDesc;
    case 'packingTemplateHomePrep':
      return l10n.packingTemplateHomePrep;
    case 'packingTemplateHomePrepDesc':
      return l10n.packingTemplateHomePrepDesc;
    case 'packingTemplateItemBabyBooks':
      return l10n.packingTemplateItemBabyBooks;
    case 'packingTemplateItemBabyBoosterSeat':
      return l10n.packingTemplateItemBabyBoosterSeat;
    case 'packingTemplateItemBabySippyCup':
      return l10n.packingTemplateItemBabySippyCup;
    case 'packingTemplateItemBabySnacks':
      return l10n.packingTemplateItemBabySnacks;
    case 'packingTemplateItemBabySunHat':
      return l10n.packingTemplateItemBabySunHat;
    case 'packingTemplateItemBoardingPass':
      return l10n.packingTemplateItemBoardingPass;
    case 'packingTemplateItemBusinessCards':
      return l10n.packingTemplateItemBusinessCards;
    case 'packingTemplateItemCampingStove':
      return l10n.packingTemplateItemCampingStove;
    case 'packingTemplateItemClothBeanie':
      return l10n.packingTemplateItemClothBeanie;
    case 'packingTemplateItemClothBelt':
      return l10n.packingTemplateItemClothBelt;
    case 'packingTemplateItemClothBlouse':
      return l10n.packingTemplateItemClothBlouse;
    case 'packingTemplateItemClothCardigan':
      return l10n.packingTemplateItemClothCardigan;
    case 'packingTemplateItemClothDress':
      return l10n.packingTemplateItemClothDress;
    case 'packingTemplateItemClothFleece':
      return l10n.packingTemplateItemClothFleece;
    case 'packingTemplateItemClothFlipFlops':
      return l10n.packingTemplateItemClothFlipFlops;
    case 'packingTemplateItemClothGloves':
      return l10n.packingTemplateItemClothGloves;
    case 'packingTemplateItemClothLaundryBag':
      return l10n.packingTemplateItemClothLaundryBag;
    case 'packingTemplateItemClothLeggings':
      return l10n.packingTemplateItemClothLeggings;
    case 'packingTemplateItemClothLightJacket':
      return l10n.packingTemplateItemClothLightJacket;
    case 'packingTemplateItemClothPackingCubes':
      return l10n.packingTemplateItemClothPackingCubes;
    case 'packingTemplateItemClothPajamas':
      return l10n.packingTemplateItemClothPajamas;
    case 'packingTemplateItemClothScarf':
      return l10n.packingTemplateItemClothScarf;
    case 'packingTemplateItemClothShorts':
      return l10n.packingTemplateItemClothShorts;
    case 'packingTemplateItemClothSkirt':
      return l10n.packingTemplateItemClothSkirt;
    case 'packingTemplateItemClothSleepwear':
      return l10n.packingTemplateItemClothSleepwear;
    case 'packingTemplateItemClothSocks':
      return l10n.packingTemplateItemClothSocks;
    case 'packingTemplateItemClothSportswear':
      return l10n.packingTemplateItemClothSportswear;
    case 'packingTemplateItemClothSunHat':
      return l10n.packingTemplateItemClothSunHat;
    case 'packingTemplateItemClothSwimCover':
      return l10n.packingTemplateItemClothSwimCover;
    case 'packingTemplateItemClothThermalUnderwear':
      return l10n.packingTemplateItemClothThermalUnderwear;
    case 'packingTemplateItemClothTravelUmbrella':
      return l10n.packingTemplateItemClothTravelUmbrella;
    case 'packingTemplateItemClothTrousers':
      return l10n.packingTemplateItemClothTrousers;
    case 'packingTemplateItemClothTshirts':
      return l10n.packingTemplateItemClothTshirts;
    case 'packingTemplateItemClothUnderwear':
      return l10n.packingTemplateItemClothUnderwear;
    case 'packingTemplateItemClothWalkingShoes':
      return l10n.packingTemplateItemClothWalkingShoes;
    case 'packingTemplateItemClothWindbreaker':
      return l10n.packingTemplateItemClothWindbreaker;
    case 'packingTemplateItemClothWinterCoat':
      return l10n.packingTemplateItemClothWinterCoat;
    case 'packingTemplateItemDocBankCards':
      return l10n.packingTemplateItemDocBankCards;
    case 'packingTemplateItemDocCash':
      return l10n.packingTemplateItemDocCash;
    case 'packingTemplateItemDocCopies':
      return l10n.packingTemplateItemDocCopies;
    case 'packingTemplateItemDocEmergencyCash':
      return l10n.packingTemplateItemDocEmergencyCash;
    case 'packingTemplateItemDocEmergencyContactsPrinted':
      return l10n.packingTemplateItemDocEmergencyContactsPrinted;
    case 'packingTemplateItemDocEuropeanHealthCard':
      return l10n.packingTemplateItemDocEuropeanHealthCard;
    case 'packingTemplateItemDocHotelReservations':
      return l10n.packingTemplateItemDocHotelReservations;
    case 'packingTemplateItemDocInternationalDrivingPermit':
      return l10n.packingTemplateItemDocInternationalDrivingPermit;
    case 'packingTemplateItemDocMedicalInsurance':
      return l10n.packingTemplateItemDocMedicalInsurance;
    case 'packingTemplateItemDocPowerOfAttorney':
      return l10n.packingTemplateItemDocPowerOfAttorney;
    case 'packingTemplateItemDocRentalAgreements':
      return l10n.packingTemplateItemDocRentalAgreements;
    case 'packingTemplateItemDocStudentId':
      return l10n.packingTemplateItemDocStudentId;
    case 'packingTemplateItemDocTravelPermits':
      return l10n.packingTemplateItemDocTravelPermits;
    case 'packingTemplateItemDocVisa':
      return l10n.packingTemplateItemDocVisa;
    case 'packingTemplateItemElecActionCamera':
      return l10n.packingTemplateItemElecActionCamera;
    case 'packingTemplateItemElecBatteryCharger':
      return l10n.packingTemplateItemElecBatteryCharger;
    case 'packingTemplateItemElecBluetoothSpeaker':
      return l10n.packingTemplateItemElecBluetoothSpeaker;
    case 'packingTemplateItemElecCamera':
      return l10n.packingTemplateItemElecCamera;
    case 'packingTemplateItemElecCameraCharger':
      return l10n.packingTemplateItemElecCameraCharger;
    case 'packingTemplateItemElecCloudBackup':
      return l10n.packingTemplateItemElecCloudBackup;
    case 'packingTemplateItemElecDrone':
      return l10n.packingTemplateItemElecDrone;
    case 'packingTemplateItemElecEbookReader':
      return l10n.packingTemplateItemElecEbookReader;
    case 'packingTemplateItemElecExtensionCord':
      return l10n.packingTemplateItemElecExtensionCord;
    case 'packingTemplateItemElecHdmiCable':
      return l10n.packingTemplateItemElecHdmiCable;
    case 'packingTemplateItemElecLaptopCharger':
      return l10n.packingTemplateItemElecLaptopCharger;
    case 'packingTemplateItemElecMemoryCards':
      return l10n.packingTemplateItemElecMemoryCards;
    case 'packingTemplateItemElecMultiUsbCharger':
      return l10n.packingTemplateItemElecMultiUsbCharger;
    case 'packingTemplateItemElecNoiseCancelling':
      return l10n.packingTemplateItemElecNoiseCancelling;
    case 'packingTemplateItemElecOfflineEntertainment':
      return l10n.packingTemplateItemElecOfflineEntertainment;
    case 'packingTemplateItemElecPortableRouter':
      return l10n.packingTemplateItemElecPortableRouter;
    case 'packingTemplateItemElecPresentationRemote':
      return l10n.packingTemplateItemElecPresentationRemote;
    case 'packingTemplateItemElecProjector':
      return l10n.packingTemplateItemElecProjector;
    case 'packingTemplateItemElecSimCard':
      return l10n.packingTemplateItemElecSimCard;
    case 'packingTemplateItemElecSmartwatchCharger':
      return l10n.packingTemplateItemElecSmartwatchCharger;
    case 'packingTemplateItemElecSpareBatteries':
      return l10n.packingTemplateItemElecSpareBatteries;
    case 'packingTemplateItemElecTablet':
      return l10n.packingTemplateItemElecTablet;
    case 'packingTemplateItemElecTabletCharger':
      return l10n.packingTemplateItemElecTabletCharger;
    case 'packingTemplateItemElecUsbDrive':
      return l10n.packingTemplateItemElecUsbDrive;
    case 'packingTemplateItemElecVpnSetup':
      return l10n.packingTemplateItemElecVpnSetup;
    case 'packingTemplateItemFavoriteToy':
      return l10n.packingTemplateItemFavoriteToy;
    case 'packingTemplateItemFinalAccommodationConfirmed':
      return l10n.packingTemplateItemFinalAccommodationConfirmed;
    case 'packingTemplateItemFinalBagsWeighed':
      return l10n.packingTemplateItemFinalBagsWeighed;
    case 'packingTemplateItemFinalCashWithdrawn':
      return l10n.packingTemplateItemFinalCashWithdrawn;
    case 'packingTemplateItemFinalChargersPacked':
      return l10n.packingTemplateItemFinalChargersPacked;
    case 'packingTemplateItemFinalKeysCollected':
      return l10n.packingTemplateItemFinalKeysCollected;
    case 'packingTemplateItemFinalMedicinesPacked':
      return l10n.packingTemplateItemFinalMedicinesPacked;
    case 'packingTemplateItemFinalOutOfOffice':
      return l10n.packingTemplateItemFinalOutOfOffice;
    case 'packingTemplateItemFinalPassportChecked':
      return l10n.packingTemplateItemFinalPassportChecked;
    case 'packingTemplateItemFinalTicketsChecked':
      return l10n.packingTemplateItemFinalTicketsChecked;
    case 'packingTemplateItemFinalTransportConfirmed':
      return l10n.packingTemplateItemFinalTransportConfirmed;
    case 'packingTemplateItemFinalWalletChecked':
      return l10n.packingTemplateItemFinalWalletChecked;
    case 'packingTemplateItemFinalWeatherChecked':
      return l10n.packingTemplateItemFinalWeatherChecked;
    case 'packingTemplateItemFirstAidKit':
      return l10n.packingTemplateItemFirstAidKit;
    case 'packingTemplateItemFlashlight':
      return l10n.packingTemplateItemFlashlight;
    case 'packingTemplateItemFoodCereal':
      return l10n.packingTemplateItemFoodCereal;
    case 'packingTemplateItemFoodCoolerIce':
      return l10n.packingTemplateItemFoodCoolerIce;
    case 'packingTemplateItemFoodEnergyBars':
      return l10n.packingTemplateItemFoodEnergyBars;
    case 'packingTemplateItemFoodFruit':
      return l10n.packingTemplateItemFoodFruit;
    case 'packingTemplateItemFoodInstantCoffee':
      return l10n.packingTemplateItemFoodInstantCoffee;
    case 'packingTemplateItemFoodInstantSoup':
      return l10n.packingTemplateItemFoodInstantSoup;
    case 'packingTemplateItemFoodJuice':
      return l10n.packingTemplateItemFoodJuice;
    case 'packingTemplateItemFoodMilk':
      return l10n.packingTemplateItemFoodMilk;
    case 'packingTemplateItemFoodNuts':
      return l10n.packingTemplateItemFoodNuts;
    case 'packingTemplateItemFoodPetTreats':
      return l10n.packingTemplateItemFoodPetTreats;
    case 'packingTemplateItemFoodProteinShakes':
      return l10n.packingTemplateItemFoodProteinShakes;
    case 'packingTemplateItemFoodReusableBottles':
      return l10n.packingTemplateItemFoodReusableBottles;
    case 'packingTemplateItemFoodSandwiches':
      return l10n.packingTemplateItemFoodSandwiches;
    case 'packingTemplateItemFoodSpices':
      return l10n.packingTemplateItemFoodSpices;
    case 'packingTemplateItemFoodTeaBags':
      return l10n.packingTemplateItemFoodTeaBags;
    case 'packingTemplateItemFormalAttire':
      return l10n.packingTemplateItemFormalAttire;
    case 'packingTemplateItemHeadphones':
      return l10n.packingTemplateItemHeadphones;
    case 'packingTemplateItemHealthAntihistamine':
      return l10n.packingTemplateItemHealthAntihistamine;
    case 'packingTemplateItemHealthBlisterPlasters':
      return l10n.packingTemplateItemHealthBlisterPlasters;
    case 'packingTemplateItemHealthBloodPressureMonitor':
      return l10n.packingTemplateItemHealthBloodPressureMonitor;
    case 'packingTemplateItemHealthCoughDrops':
      return l10n.packingTemplateItemHealthCoughDrops;
    case 'packingTemplateItemHealthCovidTests':
      return l10n.packingTemplateItemHealthCovidTests;
    case 'packingTemplateItemHealthEpipen':
      return l10n.packingTemplateItemHealthEpipen;
    case 'packingTemplateItemHealthFaceMasks':
      return l10n.packingTemplateItemHealthFaceMasks;
    case 'packingTemplateItemHealthGlucoseTablets':
      return l10n.packingTemplateItemHealthGlucoseTablets;
    case 'packingTemplateItemHealthHandCream':
      return l10n.packingTemplateItemHealthHandCream;
    case 'packingTemplateItemHealthHeatingPads':
      return l10n.packingTemplateItemHealthHeatingPads;
    case 'packingTemplateItemHealthIcePack':
      return l10n.packingTemplateItemHealthIcePack;
    case 'packingTemplateItemHealthInhaler':
      return l10n.packingTemplateItemHealthInhaler;
    case 'packingTemplateItemHealthMedicalCertificate':
      return l10n.packingTemplateItemHealthMedicalCertificate;
    case 'packingTemplateItemHealthMedicalIdBracelet':
      return l10n.packingTemplateItemHealthMedicalIdBracelet;
    case 'packingTemplateItemHealthPlasters':
      return l10n.packingTemplateItemHealthPlasters;
    case 'packingTemplateItemHealthPrescriptionList':
      return l10n.packingTemplateItemHealthPrescriptionList;
    case 'packingTemplateItemHealthRehydration':
      return l10n.packingTemplateItemHealthRehydration;
    case 'packingTemplateItemHealthScissors':
      return l10n.packingTemplateItemHealthScissors;
    case 'packingTemplateItemHealthStomachRemedy':
      return l10n.packingTemplateItemHealthStomachRemedy;
    case 'packingTemplateItemHealthSunburnGel':
      return l10n.packingTemplateItemHealthSunburnGel;
    case 'packingTemplateItemHealthThermometer':
      return l10n.packingTemplateItemHealthThermometer;
    case 'packingTemplateItemHealthTweezers':
      return l10n.packingTemplateItemHealthTweezers;
    case 'packingTemplateItemHealthVitamins':
      return l10n.packingTemplateItemHealthVitamins;
    case 'packingTemplateItemHikingBoots':
      return l10n.packingTemplateItemHikingBoots;
    case 'packingTemplateItemHomeAppliancesOff':
      return l10n.packingTemplateItemHomeAppliancesOff;
    case 'packingTemplateItemHomeBillsPaid':
      return l10n.packingTemplateItemHomeBillsPaid;
    case 'packingTemplateItemHomeCleaningDone':
      return l10n.packingTemplateItemHomeCleaningDone;
    case 'packingTemplateItemHomeCurtainsDrawn':
      return l10n.packingTemplateItemHomeCurtainsDrawn;
    case 'packingTemplateItemHomeEmergencyContactLeft':
      return l10n.packingTemplateItemHomeEmergencyContactLeft;
    case 'packingTemplateItemHomeFridgeCleared':
      return l10n.packingTemplateItemHomeFridgeCleared;
    case 'packingTemplateItemHomeGarageLocked':
      return l10n.packingTemplateItemHomeGarageLocked;
    case 'packingTemplateItemHomeGasShutoff':
      return l10n.packingTemplateItemHomeGasShutoff;
    case 'packingTemplateItemHomeLaundryDone':
      return l10n.packingTemplateItemHomeLaundryDone;
    case 'packingTemplateItemHomeMailHold':
      return l10n.packingTemplateItemHomeMailHold;
    case 'packingTemplateItemHomePlantsWatered':
      return l10n.packingTemplateItemHomePlantsWatered;
    case 'packingTemplateItemHomeSmokeDetectors':
      return l10n.packingTemplateItemHomeSmokeDetectors;
    case 'packingTemplateItemHomeValuablesSecured':
      return l10n.packingTemplateItemHomeValuablesSecured;
    case 'packingTemplateItemHomeWaterMain':
      return l10n.packingTemplateItemHomeWaterMain;
    case 'packingTemplateItemHomeWindowsClosed':
      return l10n.packingTemplateItemHomeWindowsClosed;
    case 'packingTemplateItemHygieneConditioner':
      return l10n.packingTemplateItemHygieneConditioner;
    case 'packingTemplateItemHygieneContactLens':
      return l10n.packingTemplateItemHygieneContactLens;
    case 'packingTemplateItemHygieneContactSolution':
      return l10n.packingTemplateItemHygieneContactSolution;
    case 'packingTemplateItemHygieneCottonSwabs':
      return l10n.packingTemplateItemHygieneCottonSwabs;
    case 'packingTemplateItemHygieneDentalFloss':
      return l10n.packingTemplateItemHygieneDentalFloss;
    case 'packingTemplateItemHygieneGlasses':
      return l10n.packingTemplateItemHygieneGlasses;
    case 'packingTemplateItemHygieneHairTies':
      return l10n.packingTemplateItemHygieneHairTies;
    case 'packingTemplateItemHygieneHairbrush':
      return l10n.packingTemplateItemHygieneHairbrush;
    case 'packingTemplateItemHygieneMakeupBag':
      return l10n.packingTemplateItemHygieneMakeupBag;
    case 'packingTemplateItemHygieneMoisturizer':
      return l10n.packingTemplateItemHygieneMoisturizer;
    case 'packingTemplateItemHygieneMouthwash':
      return l10n.packingTemplateItemHygieneMouthwash;
    case 'packingTemplateItemHygieneNailClippers':
      return l10n.packingTemplateItemHygieneNailClippers;
    case 'packingTemplateItemHygienePeriodProducts':
      return l10n.packingTemplateItemHygienePeriodProducts;
    case 'packingTemplateItemHygieneRazor':
      return l10n.packingTemplateItemHygieneRazor;
    case 'packingTemplateItemHygieneShampoo':
      return l10n.packingTemplateItemHygieneShampoo;
    case 'packingTemplateItemHygieneShavingCream':
      return l10n.packingTemplateItemHygieneShavingCream;
    case 'packingTemplateItemHygieneToiletryBag':
      return l10n.packingTemplateItemHygieneToiletryBag;
    case 'packingTemplateItemHygieneTravelTowel':
      return l10n.packingTemplateItemHygieneTravelTowel;
    case 'packingTemplateItemHygieneWetWipes':
      return l10n.packingTemplateItemHygieneWetWipes;
    case 'packingTemplateItemIdentityDocument':
      return l10n.packingTemplateItemIdentityDocument;
    case 'packingTemplateItemLaptop':
      return l10n.packingTemplateItemLaptop;
    case 'packingTemplateItemLeash':
      return l10n.packingTemplateItemLeash;
    case 'packingTemplateItemMedicines':
      return l10n.packingTemplateItemMedicines;
    case 'packingTemplateItemNotebook':
      return l10n.packingTemplateItemNotebook;
    case 'packingTemplateItemPassport':
      return l10n.packingTemplateItemPassport;
    case 'packingTemplateItemPetCarrier':
      return l10n.packingTemplateItemPetCarrier;
    case 'packingTemplateItemPetFood':
      return l10n.packingTemplateItemPetFood;
    case 'packingTemplateItemPetHealthRecords':
      return l10n.packingTemplateItemPetHealthRecords;
    case 'packingTemplateItemPetWaterBowl':
      return l10n.packingTemplateItemPetWaterBowl;
    case 'packingTemplateItemPhoneCharger':
      return l10n.packingTemplateItemPhoneCharger;
    case 'packingTemplateItemRainJacket':
      return l10n.packingTemplateItemRainJacket;
    case 'packingTemplateItemRtAllergyMeds':
      return l10n.packingTemplateItemRtAllergyMeds;
    case 'packingTemplateItemRtAntisepticWipes':
      return l10n.packingTemplateItemRtAntisepticWipes;
    case 'packingTemplateItemRtBandages':
      return l10n.packingTemplateItemRtBandages;
    case 'packingTemplateItemRtBookingConfirmations':
      return l10n.packingTemplateItemRtBookingConfirmations;
    case 'packingTemplateItemRtChangeOfClothes':
      return l10n.packingTemplateItemRtChangeOfClothes;
    case 'packingTemplateItemRtChargingCables':
      return l10n.packingTemplateItemRtChargingCables;
    case 'packingTemplateItemRtCoffeeTea':
      return l10n.packingTemplateItemRtCoffeeTea;
    case 'packingTemplateItemRtComfortableShoes':
      return l10n.packingTemplateItemRtComfortableShoes;
    case 'packingTemplateItemRtCoolBag':
      return l10n.packingTemplateItemRtCoolBag;
    case 'packingTemplateItemRtDeodorant':
      return l10n.packingTemplateItemRtDeodorant;
    case 'packingTemplateItemRtDepartureTimeSet':
      return l10n.packingTemplateItemRtDepartureTimeSet;
    case 'packingTemplateItemRtEmergencyContacts':
      return l10n.packingTemplateItemRtEmergencyContacts;
    case 'packingTemplateItemRtEyeDrops':
      return l10n.packingTemplateItemRtEyeDrops;
    case 'packingTemplateItemRtHandSanitizer':
      return l10n.packingTemplateItemRtHandSanitizer;
    case 'packingTemplateItemRtHandSoap':
      return l10n.packingTemplateItemRtHandSoap;
    case 'packingTemplateItemRtHatCap':
      return l10n.packingTemplateItemRtHatCap;
    case 'packingTemplateItemRtInsectRepellent':
      return l10n.packingTemplateItemRtInsectRepellent;
    case 'packingTemplateItemRtLipBalm':
      return l10n.packingTemplateItemRtLipBalm;
    case 'packingTemplateItemRtMotionSickness':
      return l10n.packingTemplateItemRtMotionSickness;
    case 'packingTemplateItemRtNonPerishableFood':
      return l10n.packingTemplateItemRtNonPerishableFood;
    case 'packingTemplateItemRtNotifyNeighbor':
      return l10n.packingTemplateItemRtNotifyNeighbor;
    case 'packingTemplateItemRtOfflineMaps':
      return l10n.packingTemplateItemRtOfflineMaps;
    case 'packingTemplateItemRtPainRelievers':
      return l10n.packingTemplateItemRtPainRelievers;
    case 'packingTemplateItemRtPaymentReady':
      return l10n.packingTemplateItemRtPaymentReady;
    case 'packingTemplateItemRtPetMailCare':
      return l10n.packingTemplateItemRtPetMailCare;
    case 'packingTemplateItemRtPhoneCharged':
      return l10n.packingTemplateItemRtPhoneCharged;
    case 'packingTemplateItemRtPortablePowerBank':
      return l10n.packingTemplateItemRtPortablePowerBank;
    case 'packingTemplateItemRtRestStops':
      return l10n.packingTemplateItemRtRestStops;
    case 'packingTemplateItemRtReusableCutlery':
      return l10n.packingTemplateItemRtReusableCutlery;
    case 'packingTemplateItemRtSecureHome':
      return l10n.packingTemplateItemRtSecureHome;
    case 'packingTemplateItemRtSecurityAlarm':
      return l10n.packingTemplateItemRtSecurityAlarm;
    case 'packingTemplateItemRtSetHeatingWater':
      return l10n.packingTemplateItemRtSetHeatingWater;
    case 'packingTemplateItemRtShowerGel':
      return l10n.packingTemplateItemRtShowerGel;
    case 'packingTemplateItemRtSpareHouseKey':
      return l10n.packingTemplateItemRtSpareHouseKey;
    case 'packingTemplateItemRtTakeOutTrash':
      return l10n.packingTemplateItemRtTakeOutTrash;
    case 'packingTemplateItemRtThermosFlask':
      return l10n.packingTemplateItemRtThermosFlask;
    case 'packingTemplateItemRtTimerLights':
      return l10n.packingTemplateItemRtTimerLights;
    case 'packingTemplateItemRtTissues':
      return l10n.packingTemplateItemRtTissues;
    case 'packingTemplateItemRtToothpaste':
      return l10n.packingTemplateItemRtToothpaste;
    case 'packingTemplateItemRtTravelInsurance':
      return l10n.packingTemplateItemRtTravelInsurance;
    case 'packingTemplateItemRtTravelMugs':
      return l10n.packingTemplateItemRtTravelMugs;
    case 'packingTemplateItemRtTravelSicknessBags':
      return l10n.packingTemplateItemRtTravelSicknessBags;
    case 'packingTemplateItemRtUnplugAppliances':
      return l10n.packingTemplateItemRtUnplugAppliances;
    case 'packingTemplateItemRtUtilityShutoff':
      return l10n.packingTemplateItemRtUtilityShutoff;
    case 'packingTemplateItemRtWetWipesFood':
      return l10n.packingTemplateItemRtWetWipesFood;
    case 'packingTemplateItemSandals':
      return l10n.packingTemplateItemSandals;
    case 'packingTemplateItemSleepingBag':
      return l10n.packingTemplateItemSleepingBag;
    case 'packingTemplateItemSnacks':
      return l10n.packingTemplateItemSnacks;
    case 'packingTemplateItemSummerBeachBag':
      return l10n.packingTemplateItemSummerBeachBag;
    case 'packingTemplateItemSummerBeachUmbrella':
      return l10n.packingTemplateItemSummerBeachUmbrella;
    case 'packingTemplateItemSummerWaterShoes':
      return l10n.packingTemplateItemSummerWaterShoes;
    case 'packingTemplateItemSunglasses':
      return l10n.packingTemplateItemSunglasses;
    case 'packingTemplateItemSunscreen':
      return l10n.packingTemplateItemSunscreen;
    case 'packingTemplateItemSwimwear':
      return l10n.packingTemplateItemSwimwear;
    case 'packingTemplateItemTent':
      return l10n.packingTemplateItemTent;
    case 'packingTemplateItemTicket':
      return l10n.packingTemplateItemTicket;
    case 'packingTemplateItemToothbrush':
      return l10n.packingTemplateItemToothbrush;
    case 'packingTemplateItemTowel':
      return l10n.packingTemplateItemTowel;
    case 'packingTemplateItemTravelAdapter':
      return l10n.packingTemplateItemTravelAdapter;
    case 'packingTemplateItemWallet':
      return l10n.packingTemplateItemWallet;
    case 'packingTemplateItemWarmLayers':
      return l10n.packingTemplateItemWarmLayers;
    case 'packingTemplateItemWaterBottle':
      return l10n.packingTemplateItemWaterBottle;
    case 'packingTemplateItemWeatherAppropriateClothing':
      return l10n.packingTemplateItemWeatherAppropriateClothing;
    case 'packingTemplateMountains':
      return l10n.packingTemplateMountains;
    case 'packingTemplateMountainsDesc':
      return l10n.packingTemplateMountainsDesc;
    case 'packingTemplateNotePrescriptionMeds':
      return l10n.packingTemplateNotePrescriptionMeds;
    case 'packingTemplateToiletries':
      return l10n.packingTemplateToiletries;
    case 'packingTemplateToiletriesDesc':
      return l10n.packingTemplateToiletriesDesc;
    case 'packingTemplateTrainBusTravel':
      return l10n.packingTemplateTrainBusTravel;
    case 'packingTemplateTrainBusTravelDesc':
      return l10n.packingTemplateTrainBusTravelDesc;
    case 'packingTemplateTravellingWithChild':
      return l10n.packingTemplateTravellingWithChild;
    case 'packingTemplateTravellingWithChildDesc':
      return l10n.packingTemplateTravellingWithChildDesc;
    case 'packingTemplateTravellingWithPet':
      return l10n.packingTemplateTravellingWithPet;
    case 'packingTemplateTravellingWithPetDesc':
      return l10n.packingTemplateTravellingWithPetDesc;
    case 'packingTemplateUnitPack':
      return l10n.packingTemplateUnitPack;
    case 'packingTemplateUnitPair':
      return l10n.packingTemplateUnitPair;
    case 'packingTemplateUnitPiece':
      return l10n.packingTemplateUnitPiece;
    case 'packingTemplateUnitSet':
      return l10n.packingTemplateUnitSet;
    default:
      return null;
  }
}
